version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9

conda:
  environment: docs/python/environment.yaml

submodules:
  include: all
  recursive: true

sphinx:
  configuration: docs/python/src/conf.py